default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
  database: the_office_db

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
  database: the_office_db_test

staging:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
